version: "3.9"
services:
  bot:
    build: .
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/code
    networks:
      main:
        aliases:
          - bot
  api:
    build: ./services/battle-api
    ports:
      - "4000:4000"
    expose:
      - 4000
    networks:
      main:
        aliases:
          - api

networks:
  main: