version: "3.9"
services:
  bot:
    tty: true
    build: .
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/code
    networks:
      main:
        aliases:
          - bot
  api:
    build: ./services/battle-api
    ports:
      - "4000:4000"
    expose:
      - 4000
    networks:
      main:
        aliases:
          - api
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      main:
        aliases:
          - db

networks:
  main:
volumes:
  mongodb_data_container:
