version: "3.9"
services:
  bot:
    tty: true
    build: .
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/code
    networks:
      main:
        aliases:
          - bot
    environment:
      - BROCK_ENVIRONMENT=prod
    restart: unless-stopped
  api:
    build: ./services/battle-api
    expose:
      - 4000
    networks:
      main:
        aliases:
          - api
    restart: unless-stopped
  db:
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      main:
        aliases:
          - db
    restart: unless-stopped

networks:
  main:
volumes:
  mongodb_data_container:
