version: "3.9"
services:
  bot:
    build: .
    network_mode: "bridge"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  api:
    build: ./services/battle-api
    network_mode: "bridge"
    ports:
      - "4000:4000"
