name: pkmn-discord
channels:
  - defaults
dependencies:
  - python=3.9.2
  - pip:
    - aiohttp
    - discord.py
    - jsonpickle
    - quart
    - distest==0.6.1
    - mypy==0.812
    - pydocstyle
    - yapf
    - pre-commit
